### ISSUE TITLE
To-do list for 1.1.0 version

### ISSUE THREAD

**Issue by mAKEkr** [mAKEkr/vuepress-plugin-blog-advance#1]
# Problem
unstable release

# To-do List
- [x] add feed sort work on feed
- [x] make feed limit count
- [x] `_drafts` don't compile on build
  - Replacement into return 404 page
- [x] fix packages.json
- [x] 1.1.0 release
